<div id="welcome">
    <h1> Zend Framework </h1>

    <h3>GSB - ZEND</h3>

    
<a href="<?php echo $this->url(array('controller' => 'locataires', 'action' => 'index')); ?>">Voir les locataires</a>   
<a href="<?php echo $this->url(array('controller' => 'appartements', 'action' => 'index')); ?>">Voir les apparts</a>
<a href="<?php echo $this->url(array('controller' => 'proprietaires', 'action' => 'index')); ?>">Voir les proprietaires</a>
<a href="<?php echo $this->url(array('controller' => 'client', 'action' => 'index')); ?>">Voir les clients</a>
<a href="<?php echo $this->url(array('controller' => 'visite', 'action' => 'index')); ?>">Voir les visites</a>
<a href="<?php echo $this->url(array('controller' => 'cotisations', 'action' => 'index')); ?>">Voir les cotisations</a>
<a href="<?php echo $this->url(array('controller' => 'recherche', 'action' => 'rechercheappart'));?>">Faire une recherche</a>
