    <br /><br />
       <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Retour</a> 
    <div id="view-content">
        <p>Details du <b>locataire</b>
    </div>
     <a href="<?php echo $this->url(array('controller' => 'locataires', 'action' => 'ajouter')); ?>">Ajouter Locataires</a> 
    <table border="1">
        <tr>
            <td>Numero de locataire</td>
     
            <td> Nom locataire</td>
     
            <td> Prenom locataire</td>
     
            <td> Date naissance </td>
     
            <td> Tel</td>
     
            <td> RIB</td>
     
            <td> Banque</td>
     
            <td> Rue Banque</td>
     
            <td> Code ville Banque</td>
     
             <td>Tel banque</td>
     
       
     </tr>
        
    </html>
  
            <tr>
                <td><?php echo $this->leslocataires['NUMEROLOC'];?></td></td>
     
                <td><?php echo $this->leslocataires['NOM_LOC'];?></td></td>
     
                <td><?php echo $this->leslocataires['PRENOM_LOC'];?></td></td>
                
                 <td><?php echo $this->leslocataires['DATENAISS'];?></td></td>
     
                <td><?php echo $this->leslocataires['TEL_LOC'];?></td></td>
     
                <td><?php echo $this->leslocataires['R_I_B'];?></td></td>
     
                <td><?php echo $this->leslocataires['BANQUE'];?></td></td>
     
                <td><?php echo $this->leslocataires['RUE_BANQUE'];?></td></td>
     
                <td><?php echo $this->leslocataires['CODEVILLE_BANQUE'];?></td></td>
     
                <td><?php echo $this->leslocataires['TEL_BANQUE'];?></td></td>
     
                <td><a href="<?php echo $this->url(array('controller' => 'locataires', 'action' => 'modifier', 'NUMEROLOC' => $this->leslocataires['NUMEROLOC'])); ?>">Modifier</a></td>
                
                <td><a href="<?php echo $this->url(array('controller' => 'locataires', 'action' => 'supprimer', 'NUMEROLOC'=> $this->leslocataires['NUMEROLOC'])); ?>">Supprimer</a></td>
     
                
     
            </tr>
    </table>