       <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Retour</a> 
<br /><br />
<div id="view-content">
    <p>Details du <b>proprietaire</b>
</div>
<a href="<?php echo $this->url(array('controller' => 'proprietaires', 'action' => 'ajouter')); ?>">Ajouter Proprietaires</a> 
<table border="1">
    <tr>
        <td>Numero du proprietaire</td>

        <td> Nom proprietaire</td>

        <td> Prenom proprietaire</td>

        <td> Adresse proprietaire </td>

        <td> code ville</td>

        <td> Tel</td>


    </tr>

</html>

    <tr>
        <td><?php echo $this->lesproprietaires["NUMEROPROP"]; ?></td>

        <td><?php echo $this->lesproprietaires["NOM"]; ?></td>

        <td><?php echo $this->lesproprietaires["PRENOM"]; ?></td>

        <td><?php echo $this->lesproprietaires["ADRESSE"]; ?></td>

        <td><?php echo $this->lesproprietaires["CODE_VILLE"]; ?></td>

        <td><?php echo $this->lesproprietaires["TEL"]; ?></td>

        <td><a href="<?php echo $this->url(array('controller' => 'proprietaires', 'action' => 'modifier', 'NUMEROPROP'=> $this->lesproprietaires["NUMEROPROP"])); ?>">Modifier</a></td>
                
        <td><a href="<?php echo $this->url(array('controller' => 'proprietaires', 'action' => 'supprimer', 'NUMEROPROP'=> $this->lesproprietaires["NUMEROPROP"])); ?>">Supprimer</a></td>

    </tr>
    
</table>