<p> Voulez vous supprimer l'appartement numero
    '<?php echo $this->appartements['NUMAPPART'];
    ?> '.
</p>
<form action="<?php echo $this->url(array('controller' => 'Appartements', 'action' => 'supprimer')); ?>" method="post">
    <div>
        
        <input type="hidden" name="NUMAPPART" value="<?php echo $this->appartements['NUMAPPART']; ?>"/>
        <input type="submit" name="supprimer" value="oui"/>
        <input type="submit" name="supprimer" value="non"/>
        
    </div>
</form>
        